training:
  n_epochs: 1
  precision: bf16-mixed
  eval_every_steps: 10000
  # W&B project to log to. Set to 'offline' to disable logging entirely.
  wandb_project: ptp-distill
  check_point_interval:
    minutes: 30
model:
  _target_: ptp.lit.ParallelSamplingLightningModule
  optim_cfg:
    lr: 0.0001
    lr_warmup: 1000
  model:
    _target_: ptp.transformer.MixedTransformerModel
    model_id: lmsys/vicuna-7b-v1.5
    dtype: float16
    cache_dir: checkpoints/.cache
    lora_config:
      r: 128
      target_modules: all-linear

data:
  _target_: ptp.data.load.PregeneratedDataModule
  root_dir: EXP_DIR/data
  tokenizer: lmsys/vicuna-7b-v1.5
  # How many completions per above packed document & how long each completion is
  num_completions: 128
  train_completion_len: 16
  # How many parallel packed documents to work on per GPU
  batch_size: 2
  num_workers: 4
