"""
Integration test: ptp_distill (prompt-scheme-distill mode) → ptp_pregenerate.

Verifies that the pregenerate.yaml generated by ptp_distill for prompt-scheme-distill
mode can actually be used to run pregeneration end-to-end. Uses a tiny fake teacher
(a minimal nn.Module with a real GPT-2 tokenizer and a stub generate()) and a tiny
in-memory dataset so the test runs without a GPU or large downloads.
"""
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest
import torch
import yaml
from datasets import Dataset

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import ptp.cli.distill as distill_module
import ptp.data.pregenerate as pregenerate_module
from ptp.data.pregenerate import main as pregenerate_main


# ---------------------------------------------------------------------------
# Fake teacher model
# ---------------------------------------------------------------------------

def _make_fake_teacher(tokenizer):
    """
    Return a fake TransformerModel-compatible object.
    Has a real tokenizer, a stub generate() that outputs random tokens,
    and no-op eval()/to() so it works on CPU without flex_attention.
    """

    class FakeTransformerModel(torch.nn.Module):
        def __init__(self, **kwargs):
            super().__init__()
            self.tokenizer = tokenizer

        def generate(
            self, input_ids, attention_mask, max_new_tokens,
            do_sample, pad_token_id, temperature, top_p, top_k,
            output_scores, return_dict_in_generate, num_return_sequences,
            use_cache,
        ):
            from transformers.generation.utils import GenerateDecoderOnlyOutput
            P = input_ids.shape[1]
            V = self.tokenizer.vocab_size
            completions = torch.randint(
                0, V, (num_return_sequences, max_new_tokens),
                device=input_ids.device,
            )
            sequences = torch.cat(
                [input_ids.expand(num_return_sequences, -1), completions], dim=1
            )
            # Uniform probability distribution over vocab, one tensor per step
            scores = tuple(
                torch.full((num_return_sequences, V), 1.0 / V, device=input_ids.device)
                for _ in range(max_new_tokens)
            )
            return GenerateDecoderOnlyOutput(sequences=sequences, scores=scores)

        def eval(self):
            return self

        def to(self, device):
            return self

    return FakeTransformerModel


# ---------------------------------------------------------------------------
# Helpers shared with test_cli.py
# ---------------------------------------------------------------------------

def _run_distill(tmp_path, monkeypatch, argv):
    monkeypatch.setattr(distill_module, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(distill_module, "CHECKPOINTS_DIR", tmp_path / "checkpoints")
    monkeypatch.setattr(distill_module, "CONFIGS_DIR", Path(__file__).parent.parent / "configs")
    monkeypatch.setattr(distill_module, "_has_chat_template", lambda _: True)
    monkeypatch.setattr(sys, "argv", ["ptp_distill"] + argv)
    distill_module.main()


def _exp_dir(tmp_path, model="myorg/tiny-model", dataset="myorg/tiny-dataset"):
    return (
        tmp_path / "checkpoints"
        / f"{distill_module.slugify(model)}_{distill_module.slugify(dataset)}"
    )


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------

def test_pregenerate_prompt_scheme_distill(tmp_path, monkeypatch):
    """
    Full pipeline test for the prompt-scheme-distill mode:
      1. ptp_distill generates pregenerate.yaml and train.yaml.
      2. pregenerate.main() parses that yaml, instantiates PromptSchemeDataModule,
         and runs one pregeneration pass.
      3. The output data directory exists and contains at least the train split.
    """
    MODEL = "myorg/tiny-model"
    DATASET = "myorg/tiny-dataset"
    PROMPT_SCHEME = "Review: {review}\nSentiment: "

    # Step 1: Generate the experiment directory.
    _run_distill(
        tmp_path, monkeypatch,
        [
            MODEL, DATASET,
            "--mode", "prompt-scheme-distill",
            "--prompt-scheme", PROMPT_SCHEME,
            "--max-sequence-length", "64",
            "--completion-length", "8",
            "--no-lora",
        ],
    )

    exp_dir = _exp_dir(tmp_path, model=MODEL, dataset=DATASET)
    assert (exp_dir / "pregenerate.yaml").exists(), "pregenerate.yaml was not created"
    assert (exp_dir / "train.yaml").exists(), "train.yaml was not created"

    # Verify that the prompt scheme is correctly encoded in the YAML.
    with open(exp_dir / "pregenerate.yaml") as f:
        pregen_config = yaml.safe_load(f)
    assert pregen_config["data"]["prompt_scheme"] == PROMPT_SCHEME
    assert pregen_config["data"]["_target_"] == "ptp.data.PromptSchemeDataModule"

    # Step 2: Patch the heavy dependencies before running pregenerate.main().

    # Fake teacher: no GPU, no flex_attention, no HuggingFace weights needed.
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    tokenizer.pad_token = tokenizer.eos_token
    FakeTeacher = _make_fake_teacher(tokenizer)
    monkeypatch.setattr(pregenerate_module, "TransformerModel", FakeTeacher)

    # Tiny dataset: 4 items with the field referenced by PROMPT_SCHEME.
    tiny_ds = Dataset.from_dict({"review": ["good", "bad", "ok", "great"]})
    monkeypatch.setattr(
        "ptp.data.prompt_scheme.load_dataset",
        lambda *args, **kwargs: tiny_ds,
    )

    # Step 3: Run pregeneration.
    pregenerate_main(
        experiment_dir=exp_dir,
        precision="float32",
        batch_size=2,
        store_interval=100,
    )

    # Step 4: Assert output structure.
    data_dir = exp_dir / "data"
    assert data_dir.exists(), "data/ directory was not created"
    assert (data_dir / "train").exists(), "data/train split was not created"
