data:
  _target_: ptp.data.load.PregeneratedDataModule
  root_dir: EXP_DIR/data
  tokenizer: __MODEL_ID__
  # How many completions per above packed document & how long each completion is
  num_completions: __NUM_COMPLETIONS__
  train_completion_len: __COMPLETION_LENGTH__
  # How many parallel packed documents to work on per GPU
  batch_size: 8
  num_workers: 4
